"""THE MOST IMPORTANT EMPIRICAL TEST.

test_predict.py asserts the thesis holds in the PREDICTION. This asserts it holds in the MEASURED
evidence: it reads evidence/observed-matrix.json (regenerated by `python -m
cheat_oracle.harness.full_matrix` against real containers), re-derives its receipt so a hand-edited
number is caught, and requires that canary-mint caught strictly more than HVTB, that an honest floor
remains, that the two out-of-reach channels are genuinely recovered, and that the only
predicted-vs-observed disagreement is the one documented substrate case.

If the artifact is absent (a machine with no docker), the test skips with a clear message rather
than passing vacuously - a green run must not be able to mean "never measured".
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cheat_oracle.canonical import receipt
from cheat_oracle.model.predict import PREDICTED

EVIDENCE = Path(__file__).resolve().parent.parent / "evidence" / "observed-matrix.json"


def _load() -> dict[str, object]:
    if not EVIDENCE.exists():
        pytest.skip("evidence/observed-matrix.json absent; run full_matrix against docker first")
    return dict(json.loads(EVIDENCE.read_text()))


def test_receipt_matches_so_the_numbers_were_not_hand_edited() -> None:
    rec = _load()
    stored = rec.pop("receipt")
    assert receipt(rec) == stored, "evidence receipt does not match its content"


def test_fix_catches_strictly_more_and_floor_remains() -> None:
    rec = _load()
    disc = rec["analysis"]["discrimination"]  # type: ignore[index]
    assert disc["fix_catches_strictly_more"] is True
    assert disc["floor_nonempty"] is True


def _analysis() -> dict[str, object]:
    a = _load()["analysis"]
    assert isinstance(a, dict)
    return a


def _set(a: dict[str, object], key: str) -> set[str]:
    v = a[key]
    assert isinstance(v, list)
    return set(v)


def test_the_measured_ladder_holds() -> None:
    # Each rung recovers what the model says it isolates, measured cell by cell.
    a = _analysis()
    disc = a["discrimination"]
    assert isinstance(disc, dict)
    # d1 (inode scope alone) recovers exactly the hardlink channel over d0's directory watch.
    assert _set(a, "recovered_d1_over_d0") == {"c02"}
    assert disc["d1_recovers_over_d0"] is True
    # d3 (superblock + out-of-namespace + fail-closed) recovers what an inode watch still misses:
    # the git object-store reads and the two detector-attack channels.
    assert {"c04", "c05", "c10", "c11"} <= _set(a, "recovered_d3_over_d1")
    assert disc["fix_beats_inode_watch"] is True


def test_d2_mount_mark_is_blind_out_of_container() -> None:
    # The measured reason the fix marks the superblock, not the mount: an out-of-container mount
    # mark watches its own vfsmount and sees none of the subject's reads.
    a = _analysis()
    disc = a["discrimination"]
    assert isinstance(disc, dict)
    assert a["d2_out_of_container_caught"] == [], a["d2_out_of_container_caught"]
    assert disc["d2_blind_out_of_container"] is True


def test_out_of_reach_channels_are_recovered() -> None:
    # The money result: killing HVTB's in-container watcher (c10) and unlinking its flag (c11)
    # defeat it, and canary-mint - in a separate namespace - catches the read anyway.
    rec = _load()
    recovered = set(rec["analysis"]["recovered_by_fix"])  # type: ignore[index]
    assert {"c10", "c11"} <= recovered, recovered


def test_floor_contains_the_content_duplication_channels() -> None:
    rec = _load()
    floor = set(rec["analysis"]["d3_undercount_floor"])  # type: ignore[index]
    assert {"c03", "c12"} <= floor, floor


def test_only_documented_disagreement_is_the_overflow_substrate_case() -> None:
    rec = _load()
    disagreements = rec["analysis"]["disagreements"]  # type: ignore[index]
    channels = {d["channel"] for d in disagreements}
    assert channels <= {"c08"}, f"unexpected model-vs-observation disagreement: {channels}"


def test_the_disagreement_list_is_re_derivable_from_the_observed_cells() -> None:
    # The assertion above is a subset check, so an EMPTY disagreement list satisfies it. A new
    # model-vs-observation gap could be hidden by deleting the row rather than explaining it,
    # leaving "predicted == observed except c08" true only because nothing else was recorded. So
    # recompute the whole list from the observed verdicts and the model, and demand an exact match.
    # d2 is measured but deliberately not diffed cell-by-cell (results/04), so it is not derived.
    rec = _load()
    observed = rec["observed"]
    assert isinstance(observed, dict)
    derived: set[tuple[str, str]] = set()
    for cid, cell in observed.items():
        assert isinstance(cell, dict)
        for did in ("d0", "d1", "d3"):
            if cell.get(f"{did}_status") != "OK":
                continue
            if cell.get(did) != PREDICTED[cid][did].verdict.value:
                derived.add((str(cid), did))
    disagreements = rec["analysis"]["disagreements"]  # type: ignore[index]
    assert isinstance(disagreements, list)
    recorded = {(str(dict(d)["channel"]), str(dict(d)["detector"])) for d in disagreements}
    assert derived == recorded, f"recorded {recorded} but the cells say {derived}"


# The sets README.md and RESULTS.md publish from this artifact, written out so a change has to edit
# this line and explain itself. Subset checks elsewhere in this file cannot catch an INFLATED claim.
PUBLISHED = {
    "d0_undercount": {"c02", "c03", "c04", "c05", "c10", "c11", "c12"},
    "d1_undercount": {"c03", "c04", "c05", "c10", "c11", "c12"},
    "d2_out_of_container_caught": set(),
    "d3_undercount_floor": {"c03", "c12"},
    "recovered_by_fix": {"c02", "c04", "c05", "c10", "c11"},
    "recovered_d1_over_d0": {"c02"},
    "recovered_d3_over_d1": {"c04", "c05", "c10", "c11"},
}


def test_the_published_sets_are_exactly_what_the_readme_claims() -> None:
    # "canary-mint recovers 5" and "the honest floor is c03/c12/c13" are exact claims. Asserting
    # only `{"c10","c11"} <= recovered` would let a fix that claimed to catch everything pass.
    a = _analysis()
    for key, expected in PUBLISHED.items():
        assert _set(a, key) == expected, f"{key}: {_set(a, key)} != {expected}"


def test_the_published_sets_are_re_derivable_from_the_observed_cells() -> None:
    # The summary block is a convenience over the per-cell verdicts. Re-derive every set from the
    # cells so an edit to the summary alone disagrees with the matrix beneath it.
    rec = _load()
    observed = rec["observed"]
    assert isinstance(observed, dict)

    def missed(detector: str) -> set[str]:
        out: set[str] = set()
        for cid, cell in observed.items():
            assert isinstance(cell, dict)
            if cell.get(f"{detector}_status") == "OK" and cell.get(detector) == "misses":
                out.add(str(cid))
        return out

    def fired(detector: str) -> set[str]:
        out: set[str] = set()
        for cid, cell in observed.items():
            assert isinstance(cell, dict)
            if cell.get(f"{detector}_status") == "OK" and cell.get(detector) == "fires":
                out.add(str(cid))
        return out

    a = _analysis()
    d0, d1, d3 = missed("d0"), missed("d1"), missed("d3")
    assert _set(a, "d0_undercount") == d0
    assert _set(a, "d1_undercount") == d1
    assert _set(a, "d3_undercount_floor") == d3
    assert _set(a, "d2_out_of_container_caught") == fired("d2")
    assert _set(a, "recovered_by_fix") == d0 - d3
    assert _set(a, "recovered_d1_over_d0") == d0 - d1
    assert _set(a, "recovered_d3_over_d1") == d1 - d3

    disc = a["discrimination"]
    assert isinstance(disc, dict)
    assert disc["fix_catches_strictly_more"] is (d3 < d0)
    assert disc["floor_nonempty"] is bool(d3)
    assert disc["d1_recovers_over_d0"] is bool(d0 - d1)
    assert disc["fix_beats_inode_watch"] is bool(d1 - d3)
    assert disc["d2_blind_out_of_container"] is (not fired("d2"))


def test_sidecar_evidence_records_successful_ledger_audits() -> None:
    rec = _load()
    observed = rec["observed"]
    assert isinstance(observed, dict)
    for cid, cell in observed.items():
        assert isinstance(cell, dict)
        for det in ("d2", "d3"):
            if cell.get(f"{det}_status") != "OK":
                continue
            audit = cell.get(f"{det}_ledger_verify")
            assert isinstance(audit, dict), f"{cid}/{det} missing ledger audit"
            assert audit.get("ok") is True, f"{cid}/{det} ledger audit failed: {audit}"
