"""THE MOST IMPORTANT EMPIRICAL TEST.

test_predict.py asserts the thesis holds in the PREDICTION. This asserts it holds in the MEASURED
evidence: it reads evidence/observed-matrix.json (regenerated by `python -m
cheat_oracle.harness.full_matrix` against real containers), re-derives its receipt so a hand-edited
number is caught, and requires that canary-mint caught strictly more than HVTB, that an honest floor
remains, that the two out-of-reach channels are genuinely recovered, and that the only
predicted-vs-observed disagreement is the one documented substrate case.

If the artifact is absent (a machine with no docker), the test skips with a clear message rather
than passing vacuously - a green run must not be able to mean "never measured".
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cheat_oracle.canonical import receipt

EVIDENCE = Path(__file__).resolve().parent.parent / "evidence" / "observed-matrix.json"


def _load() -> dict[str, object]:
    if not EVIDENCE.exists():
        pytest.skip("evidence/observed-matrix.json absent; run full_matrix against docker first")
    return dict(json.loads(EVIDENCE.read_text()))


def test_receipt_matches_so_the_numbers_were_not_hand_edited() -> None:
    rec = _load()
    stored = rec.pop("receipt")
    assert receipt(rec) == stored, "evidence receipt does not match its content"


def test_fix_catches_strictly_more_and_floor_remains() -> None:
    rec = _load()
    disc = rec["analysis"]["discrimination"]  # type: ignore[index]
    assert disc["fix_catches_strictly_more"] is True
    assert disc["floor_nonempty"] is True


def _analysis() -> dict[str, object]:
    a = _load()["analysis"]
    assert isinstance(a, dict)
    return a


def _set(a: dict[str, object], key: str) -> set[str]:
    v = a[key]
    assert isinstance(v, list)
    return set(v)


def test_the_measured_ladder_holds() -> None:
    # Each rung recovers what the model says it isolates, measured cell by cell.
    a = _analysis()
    disc = a["discrimination"]
    assert isinstance(disc, dict)
    # d1 (inode scope alone) recovers exactly the hardlink channel over d0's directory watch.
    assert _set(a, "recovered_d1_over_d0") == {"c02"}
    assert disc["d1_recovers_over_d0"] is True
    # d3 (superblock + out-of-namespace + fail-closed) recovers what an inode watch still misses:
    # the git object-store reads and the two detector-attack channels.
    assert {"c04", "c05", "c10", "c11"} <= _set(a, "recovered_d3_over_d1")
    assert disc["fix_beats_inode_watch"] is True


def test_d2_mount_mark_is_blind_out_of_container() -> None:
    # The measured reason the fix marks the superblock, not the mount: an out-of-container mount
    # mark watches its own vfsmount and sees none of the subject's reads.
    a = _analysis()
    disc = a["discrimination"]
    assert isinstance(disc, dict)
    assert a["d2_out_of_container_caught"] == [], a["d2_out_of_container_caught"]
    assert disc["d2_blind_out_of_container"] is True


def test_out_of_reach_channels_are_recovered() -> None:
    # The money result: killing HVTB's in-container watcher (c10) and unlinking its flag (c11)
    # defeat it, and canary-mint - in a separate namespace - catches the read anyway.
    rec = _load()
    recovered = set(rec["analysis"]["recovered_by_fix"])  # type: ignore[index]
    assert {"c10", "c11"} <= recovered, recovered


def test_floor_contains_the_content_duplication_channels() -> None:
    rec = _load()
    floor = set(rec["analysis"]["d3_undercount_floor"])  # type: ignore[index]
    assert {"c03", "c12"} <= floor, floor


def test_only_documented_disagreement_is_the_overflow_substrate_case() -> None:
    rec = _load()
    disagreements = rec["analysis"]["disagreements"]  # type: ignore[index]
    channels = {d["channel"] for d in disagreements}
    assert channels <= {"c08"}, f"unexpected model-vs-observation disagreement: {channels}"
